import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  batchProgressContainer: {
    position: 'absolute',
    bottom: 70, // Moved higher to avoid Android navigation bar
    alignSelf: 'center',
    backgroundColor: '#1C1C1E', // sleek dark theme
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 30, // pill shape
    zIndex: 100,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
    elevation: 6,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.1)',
  },
  batchProgressText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 14,
    marginRight: 10,
  },
  centerContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  headerBlock: {
    flexDirection: 'row',
    padding: 15,
  },
  coverImage: {
    width: 100,
    height: 150,
    borderRadius: 6,
    marginRight: 15,
  },
  placeholderCover: {
    width: 100,
    height: 150,
    backgroundColor: '#333',
    borderRadius: 6,
    marginRight: 15,
  },
  infoBlock: {
    flex: 1,
    justifyContent: 'space-between',
  },
  novelTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    marginBottom: 5,
  },
  novelAuthor: {
    fontSize: 16,
    color: '#888',
    marginBottom: 8,
  },
  metadataRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    marginBottom: 15,
    gap: 10,
  },
  metadataItem: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  metadataText: {
    fontSize: 13,
    color: '#888',
    marginLeft: 4,
    fontWeight: 'bold',
  },
  badge: {
    backgroundColor: 'rgba(30, 144, 255, 0.1)',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 6,
  },
  badgeText: {
    color: '#1E90FF',
    fontSize: 12,
    fontWeight: 'bold',
    textTransform: 'uppercase',
  },
  actionRow: {
    flexDirection: 'row',
  },
  actionButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(30, 144, 255, 0.1)',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 20,
  },
  actionButtonText: {
    color: '#1E90FF',
    fontWeight: 'bold',
    marginLeft: 5,
  },
  readButtonContainer: {
    paddingHorizontal: 15,
    paddingBottom: 15,
  },
  readButton: {
    backgroundColor: '#1E90FF',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 12,
    borderRadius: 8,
  },
  readButtonText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 16,
  },
  summaryBlock: {
    padding: 15,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(150,150,150,0.2)',
  },
  summaryTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 10,
  },
  summaryText: {
    fontSize: 14,
    lineHeight: 22,
    color: '#aaa',
  },
  genreTag: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: 'rgba(150,150,150,0.3)',
    marginRight: 8,
  },
  genreText: {
    fontSize: 12,
    color: '#888',
  },
  chaptersHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    padding: 15,
    paddingBottom: 5,
  },
  chaptersTitle: {
    fontSize: 16,
    fontWeight: 'bold',
  },
  sortButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(30, 144, 255, 0.1)',
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 12,
  },
  sortText: {
    color: '#1E90FF',
    marginLeft: 5,
    fontSize: 12,
    fontWeight: 'bold',
  },
  searchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(150,150,150,0.1)',
    borderRadius: 8,
    paddingHorizontal: 12,
    height: 40,
  },
  searchInput: {
    flex: 1,
    color: '#888',
    height: '100%',
  },
  chapterCard: {
    height: 55,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 15,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(150,150,150,0.1)',
  },
  chapterClickableArea: {
    flex: 1,
    height: '100%',
    justifyContent: 'center',
    marginRight: 10,
  },
  chapterTitle: {
    fontSize: 16,
    marginRight: 10,
  },
  chapterTitleRead: {
    color: '#888',
  },

  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.7)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  // --- Redesigned Modal Styles ---
  manageModalContent: {
    width: '88%',
    backgroundColor: '#1C1C1E',
    borderRadius: 20,
    padding: 20,
    maxHeight: '75%',
    elevation: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.4,
    shadowRadius: 24,
  },
  manageModalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  manageModalHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  manageIconBg: {
    width: 36,
    height: 36,
    borderRadius: 10,
    backgroundColor: '#1E90FF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  manageModalTitle: {
    fontSize: 17,
    fontWeight: 'bold',
  },
  manageModalSubtitle: {
    fontSize: 12,
    marginTop: 1,
  },
  manageCloseBtn: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: 'rgba(255,255,255,0.08)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  manageDivider: {
    height: 1,
    backgroundColor: 'rgba(255,255,255,0.08)',
    marginVertical: 16,
  },
  manageCatList: {
    maxHeight: 280,
  },
  manageCatRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 11,
    paddingHorizontal: 8,
    borderRadius: 10,
    marginBottom: 2,
  },
  manageCatInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    flex: 1,
  },
  manageCatName: {
    fontSize: 15,
  },
  // --- Pagination Styles ---
  paginationTopBar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: 'rgba(30, 144, 255, 0.06)',
    marginHorizontal: 15,
    marginBottom: 10,
    paddingHorizontal: 12,
    height: 44,
    borderRadius: 10,
  },
  paginationInfoText: {
    fontSize: 14,
    color: '#888',
    fontWeight: '500',
  },
  paginationJumpButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    padding: 5,
  },
  paginationJumpText: {
    color: '#1E90FF',
    fontSize: 14,
    fontWeight: 'bold',
  },
  paginationBottomBar: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    paddingTop: 15,
    paddingBottom: 40,
    paddingHorizontal: 10,
    gap: 4,
  },
  pageButton: {
    minWidth: 32,
    height: 32,
    borderRadius: 16,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 4,
  },
  pageButtonActive: {
    backgroundColor: '#1E90FF',
  },
  pageButtonText: {
    fontSize: 14,
    color: '#888',
  },
  pageButtonTextActive: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#fff',
  },
  navButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    justifyContent: 'center',
    alignItems: 'center',
  },
  navButtonDisabled: {
    opacity: 0.3,
  },
  ellipsisText: {
    color: '#555',
    marginHorizontal: 4,
    fontSize: 16,
  },
  jumpModalInput: {
    backgroundColor: 'rgba(255,255,255,0.05)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.1)',
    borderRadius: 8,
    color: '#fff',
    fontSize: 16,
    paddingHorizontal: 12,
    paddingVertical: 10,
    textAlign: 'center',
    marginVertical: 15,
  },
  jumpModalActions: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 15,
    marginTop: 5,
  },
  jumpModalBtn: {
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 8,
  },
  jumpModalBtnPrimary: {
    backgroundColor: '#1E90FF',
  },
  jumpModalBtnDisabled: {
    backgroundColor: 'rgba(30, 144, 255, 0.3)',
  },
  jumpModalBtnText: {
    color: '#888',
    fontWeight: 'bold',
  },
  jumpModalBtnTextPrimary: {
    color: '#fff',
    fontWeight: 'bold',
  },
  batchModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  batchModalContent: {
    backgroundColor: '#1C1C1E',
    width: '100%',
    maxWidth: 400,
    borderRadius: 16,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 5,
  },
  batchModalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 20,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255,255,255,0.1)',
  },
  batchModalTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#fff',
  },
  batchDownloadBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.1)',
    paddingVertical: 14,
    borderRadius: 12,
    gap: 8,
  },
  batchDownloadBtnPrimary: {
    backgroundColor: '#1E90FF',
  },
  batchDownloadBtnText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
  },
  batchRangeContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 15,
    paddingTop: 15,
    borderTopWidth: 1,
    borderTopColor: 'rgba(255,255,255,0.1)',
  },
  batchRangeInput: {
    backgroundColor: 'rgba(255,255,255,0.05)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.1)',
    borderRadius: 8,
    color: '#fff',
    fontSize: 15,
    paddingHorizontal: 12,
    paddingVertical: 8,
    textAlign: 'center',
    flex: 1,
  },
  batchRangeText: {
    color: '#888',
    marginHorizontal: 10,
    fontSize: 14,
  },
  batchRangeError: {
    color: '#FF6B6B',
    fontSize: 13,
    textAlign: 'center',
    marginTop: 8,
  },
});
