import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  listContent: {
    padding: 10,
  },
  emptyContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  title: {
    fontSize: 20,
    fontWeight: 'bold',
  },
  subtitle: {
    fontSize: 16,
    color: '#888',
    marginTop: 10,
  },
  novelCard: {
    flex: 1,
    margin: 5,
    maxWidth: '33%',
  },
  coverImage: {
    width: '100%',
    aspectRatio: 2/3,
    borderRadius: 6,
  },
  placeholderCover: {
    width: '100%',
    aspectRatio: 2/3,
    borderRadius: 6,
    backgroundColor: '#333',
  },
  novelTitle: {
    marginTop: 5,
    fontSize: 12,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  tabContainer: {
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(150,150,150,0.15)',
  },
  tabScrollContent: {
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  tabButton: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
    marginRight: 8,
    backgroundColor: 'rgba(255,255,255,0.08)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.1)',
  },
  activeTabButton: {
    backgroundColor: '#1E90FF',
    borderColor: '#1E90FF',
  },
  tabText: {
    fontSize: 13,
    color: '#999',
    fontWeight: '500',
  },
  activeTabText: {
    color: '#fff',
    fontWeight: 'bold',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.7)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContent: {
    width: '85%',
    backgroundColor: '#1C1C1E',
    borderRadius: 16,
    padding: 20,
    maxHeight: '80%',
  },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 4,
    gap: 8,
  },
  modalTitle: {
    fontSize: 17,
    fontWeight: 'bold',
    flexShrink: 1,
  },
  modalSubtitle: {
    fontSize: 13,
    marginBottom: 12,
    marginLeft: 28,
  },
  modalCategoryList: {
    maxHeight: 220,
    marginBottom: 12,
  },
  modalCategoryRow: {
    paddingVertical: 11,
    paddingHorizontal: 8,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255,255,255,0.06)',
    borderRadius: 8,
  },
  activeModalCategoryRow: {
    backgroundColor: 'rgba(30,144,255,0.1)',
  },
  modalCategoryRowInner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  modalCategoryText: {
    fontSize: 15,
  },
  activeModalCategoryText: {
    fontWeight: 'bold',
  },
  removeButton: {
    marginTop: 8,
    paddingVertical: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,68,68,0.1)',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: 'rgba(255,68,68,0.2)',
  },
  removeButtonText: {
    fontSize: 15,
    fontWeight: '600',
  },
  cancelButton: {
    marginTop: 8,
    paddingVertical: 12,
    alignItems: 'center',
  },
  cancelButtonText: {
    fontSize: 15,
  },
  addCategoryContainer: {
    flexDirection: 'row',
    marginBottom: 16,
    alignItems: 'center',
  },
  addCategoryInput: {
    flex: 1,
    backgroundColor: 'rgba(255,255,255,0.06)',
    borderRadius: 10,
    paddingHorizontal: 15,
    paddingVertical: 12,
    color: '#fff',
    marginRight: 10,
    fontSize: 14,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
  },
  addButton: {
    backgroundColor: '#1E90FF',
    width: 44,
    height: 44,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  manageCategoryRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 4,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255,255,255,0.06)',
  },
  manageCategoryInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    flex: 1,
  },
  systemBadge: {
    backgroundColor: 'rgba(30,144,255,0.15)',
    borderRadius: 6,
    paddingHorizontal: 6,
    paddingVertical: 2,
    marginLeft: 4,
  },
  systemBadgeText: {
    fontSize: 10,
    color: '#1E90FF',
    fontWeight: '600',
  },
  deleteCategoryButton: {
    padding: 8,
  },
  // --- Redesigned Manage Categories Modal ---
  manageModalContent: {
    width: '88%',
    backgroundColor: '#1C1C1E',
    borderRadius: 20,
    padding: 20,
    maxHeight: '75%',
    elevation: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.4,
    shadowRadius: 24,
  },
  manageModalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  manageModalHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  manageIconBg: {
    width: 36,
    height: 36,
    borderRadius: 10,
    backgroundColor: '#1E90FF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  manageModalTitle: {
    fontSize: 17,
    fontWeight: 'bold',
  },
  manageModalSubtitle: {
    fontSize: 12,
    marginTop: 1,
  },
  manageCloseBtn: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: 'rgba(255,255,255,0.08)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  manageDivider: {
    height: 1,
    backgroundColor: 'rgba(255,255,255,0.08)',
    marginVertical: 16,
  },
  manageAddRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
  },
  manageAddInput: {
    flex: 1,
    backgroundColor: 'rgba(255,255,255,0.06)',
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 12,
    color: '#fff',
    fontSize: 14,
    marginRight: 10,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
  },
  manageAddBtn: {
    backgroundColor: '#1E90FF',
    width: 44,
    height: 44,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  manageCatList: {
    maxHeight: 280,
  },
  manageSectionHeader: {
    marginTop: 4,
    marginBottom: 8,
    paddingHorizontal: 2,
  },
  manageSectionTitle: {
    fontSize: 12,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.8,
  },
  manageCatRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 11,
    paddingHorizontal: 8,
    borderRadius: 10,
    marginBottom: 2,
  },
  manageCatInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    flex: 1,
  },
  manageCatName: {
    fontSize: 15,
  },
  manageDeleteBtn: {
    width: 34,
    height: 34,
    borderRadius: 10,
    backgroundColor: 'rgba(255,68,68,0.1)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  manageSystemTag: {
    backgroundColor: 'rgba(255,255,255,0.06)',
    borderRadius: 6,
    paddingHorizontal: 6,
    paddingVertical: 2,
    marginLeft: 2,
  },
  manageSystemTagText: {
    fontSize: 10,
    color: '#555',
    fontWeight: '600',
  },
  manageCloseButton: {
    marginTop: 14,
    paddingVertical: 13,
    alignItems: 'center',
    backgroundColor: 'rgba(30,144,255,0.1)',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(30,144,255,0.15)',
  },
  manageCloseButtonText: {
    fontSize: 15,
    fontWeight: '600',
  },
});
